# Generated by Django 3.2.8 on 2021-11-04 12:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20211028_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='company_data',
            name='company_category',
            field=models.CharField(choices=[('bolt', '볼트'), ('nut', '너트'), ('반도체', '반도체')], default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
    ]
